import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Electronics (3 products)
        {
            name: 'iPhone 15 Pro Max',
            description: 'Latest Apple flagship with A17 Pro chip and titanium design',
            category: 'Electronics',
            price: 899.99,
            quantity: 45,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop',
            sellerId: 3,
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'MacBook Air M2',
            description: 'Powerful laptop with M2 chip and stunning display',
            category: 'Electronics',
            price: 799.99,
            quantity: 30,
            isAuction: 'Y',
            expirationDate: '2024-04-15',
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop',
            sellerId: 6,
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Sony WH-1000XM5',
            description: 'Premium noise-canceling wireless headphones',
            category: 'Electronics',
            price: 349.99,
            quantity: 60,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=400&h=400&fit=crop',
            sellerId: 7,
            createdAt: new Date('2024-01-15').toISOString(),
        },
        // Fashion (3 products)
        {
            name: 'Nike Air Jordan 1',
            description: 'Iconic basketball sneakers in retro colorway',
            category: 'Fashion',
            price: 179.99,
            quantity: 85,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&h=400&fit=crop',
            sellerId: 8,
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: "Levi's 501 Original Jeans",
            description: 'Classic straight-fit denim jeans',
            category: 'Fashion',
            price: 69.99,
            quantity: 100,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
            sellerId: 9,
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Ray-Ban Aviator Sunglasses',
            description: 'Timeless aviator style with UV protection',
            category: 'Fashion',
            price: 159.99,
            quantity: 50,
            isAuction: 'Y',
            expirationDate: '2024-04-10',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop',
            sellerId: 3,
            createdAt: new Date('2024-01-22').toISOString(),
        },
        // Sports (3 products)
        {
            name: 'Wilson Pro Staff Tennis Racket',
            description: 'Professional-grade tennis racket',
            category: 'Sports',
            price: 249.99,
            quantity: 35,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1617083278237-d0a0a6878f32?w=400&h=400&fit=crop',
            sellerId: 6,
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Spalding NBA Official Basketball',
            description: 'Official size and weight basketball',
            category: 'Sports',
            price: 29.99,
            quantity: 90,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.4,
            imageUrl: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=400&fit=crop',
            sellerId: 7,
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Fitbit Charge 6',
            description: 'Advanced fitness tracker with heart rate monitoring',
            category: 'Sports',
            price: 149.99,
            quantity: 55,
            isAuction: 'Y',
            expirationDate: '2024-04-20',
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop',
            sellerId: 8,
            createdAt: new Date('2024-02-01').toISOString(),
        },
        // Tools (3 products)
        {
            name: 'DeWalt 20V Cordless Drill',
            description: 'Powerful drill driver with battery and charger',
            category: 'Tools',
            price: 199.99,
            quantity: 40,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400&h=400&fit=crop',
            sellerId: 9,
            createdAt: new Date('2024-02-03').toISOString(),
        },
        {
            name: 'Milwaukee M18 Impact Driver',
            description: 'High-torque impact driver for heavy-duty tasks',
            category: 'Tools',
            price: 229.99,
            quantity: 32,
            isAuction: 'Y',
            expirationDate: '2024-04-12',
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=400&h=400&fit=crop',
            sellerId: 3,
            createdAt: new Date('2024-02-05').toISOString(),
        },
        {
            name: 'Bosch Laser Distance Measure',
            description: 'Accurate laser measuring tool up to 165 feet',
            category: 'Tools',
            price: 89.99,
            quantity: 48,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1606092195730-5d7b9af1efc5?w=400&h=400&fit=crop',
            sellerId: 6,
            createdAt: new Date('2024-02-08').toISOString(),
        },
        // Home (3 products)
        {
            name: 'Dyson V15 Detect Vacuum',
            description: 'Cordless vacuum with laser dust detection',
            category: 'Home',
            price: 649.99,
            quantity: 25,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=400&h=400&fit=crop',
            sellerId: 7,
            createdAt: new Date('2024-02-10').toISOString(),
        },
        {
            name: 'Ninja Air Fryer',
            description: '6-quart air fryer with multiple cooking functions',
            category: 'Home',
            price: 119.99,
            quantity: 65,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.6,
            imageUrl: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop',
            sellerId: 8,
            createdAt: new Date('2024-02-12').toISOString(),
        },
        {
            name: 'Keurig K-Elite Coffee Maker',
            description: 'Single-serve coffee maker with iced coffee feature',
            category: 'Home',
            price: 169.99,
            quantity: 42,
            isAuction: 'Y',
            expirationDate: '2024-04-18',
            rating: 4.5,
            imageUrl: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400&h=400&fit=crop',
            sellerId: 9,
            createdAt: new Date('2024-02-15').toISOString(),
        },
        // Books (3 products)
        {
            name: 'The Art of War by Sun Tzu',
            description: 'Classic strategy and philosophy book',
            category: 'Books',
            price: 14.99,
            quantity: 100,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.8,
            imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop',
            sellerId: 3,
            createdAt: new Date('2024-02-18').toISOString(),
        },
        {
            name: 'Atomic Habits by James Clear',
            description: 'Bestselling self-improvement and habit formation guide',
            category: 'Books',
            price: 24.99,
            quantity: 80,
            isAuction: 'N',
            expirationDate: null,
            rating: 4.9,
            imageUrl: 'https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400&h=400&fit=crop',
            sellerId: 6,
            createdAt: new Date('2024-02-20').toISOString(),
        },
        {
            name: 'The Hobbit by J.R.R. Tolkien',
            description: 'Fantasy adventure classic, illustrated edition',
            category: 'Books',
            price: 32.99,
            quantity: 70,
            isAuction: 'Y',
            expirationDate: '2024-04-25',
            rating: 4.7,
            imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop',
            sellerId: 7,
            createdAt: new Date('2024-02-22').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});